on: [push]
jobs:
    build:
        runs-on: docker
        container:
            image: docker
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to docker
              run: docker login -u ${{ forgejo.actor }} -p ${{ secret.REGISTRY_TOKEN }} ${{ forgejo.server_url }}
            - name: Build the image
              run: docker build -t ${{ forgejo.server_url }}/${{ forgejo.repository }}:latest
            - name: Push the image
              run: docker push ${{ forgejo.server_url }}/${{ forgejo.repository }}:latest
