on: [push]
jobs:
    build:
        runs-on: docker
        container:
            image: ubuntu
        steps:
            - name: Install deps
              run: |
                # Docker APT setup
                # Add Docker's official GPG key:
                apt update
                apt install ca-certificates curl
                install -m 0755 -d /etc/apt/keyrings
                curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
                chmod a+r /etc/apt/keyrings/docker.asc

                # Add the repository to Apt sources:
                tee /etc/apt/sources.list.d/docker.sources <<EOF
                Types: deb
                URIs: https://download.docker.com/linux/ubuntu
                Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
                Components: stable
                Signed-By: /etc/apt/keyrings/docker.asc
                EOF

                apt update -y
                
                # Install NodeJS (for checkout)
                apt install -y nodejs

                # Install Docker (for build and push image)
                apt install -y docker-ce docker-ce-cli docker-buildx-plugin
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to docker
              run: docker login -u ${{ forgejo.actor }} -p ${{ secrets.REGISTRY_TOKEN }} ${{ forgejo.server_url }}
            - name: Build the image
              run: docker build -t ${{ forgejo.server_url }}/${{ forgejo.repository }}:latest
            - name: Push the image
              run: docker push ${{ forgejo.server_url }}/${{ forgejo.repository }}:latest
