// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ApiAverageScoreStatisticsGetData, ApiAverageScoreStatisticsGetResponses, ApiCreateTopicTopicPostData, ApiCreateTopicTopicPostErrors, ApiCreateTopicTopicPostResponses, ApiDeleteSubmissionSubmissionDeleteData, ApiDeleteSubmissionSubmissionDeleteErrors, ApiDeleteSubmissionSubmissionDeleteResponses, ApiDeleteTopicTopicDeleteData, ApiDeleteTopicTopicDeleteErrors, ApiDeleteTopicTopicDeleteResponses, ApiGetReviewOfSubmissionReviewOfGetData, ApiGetReviewOfSubmissionReviewOfGetErrors, ApiGetReviewOfSubmissionReviewOfGetResponses, ApiGetReviewReviewGetData, ApiGetReviewReviewGetErrors, ApiGetReviewReviewGetResponses, ApiGetReviewsReviewsGetData, ApiGetReviewsReviewsGetResponses, ApiGetSubmissionsSubmissionsGetData, ApiGetSubmissionsSubmissionsGetResponses, ApiGetSubmissionSubmissionGetData, ApiGetSubmissionSubmissionGetErrors, ApiGetSubmissionSubmissionGetResponses, ApiGetTopicsTopicsGetData, ApiGetTopicsTopicsGetErrors, ApiGetTopicsTopicsGetResponses, ApiGetTopicTopicGetData, ApiGetTopicTopicGetErrors, ApiGetTopicTopicGetResponses, ApiReviewReviewPostData, ApiReviewReviewPostErrors, ApiReviewReviewPostResponses, ApiSubmitSubmissionPostData, ApiSubmitSubmissionPostErrors, ApiSubmitSubmissionPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Api Get Reviews
 *
 * Get all reviews
 */
export const apiGetReviews = <ThrowOnError extends boolean = false>(options?: Options<ApiGetReviewsReviewsGetData, ThrowOnError>) => (options?.client ?? client).get<ApiGetReviewsReviewsGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/reviews',
    ...options
});

/**
 * Api Get Review
 *
 * Get a single review
 */
export const apiGetReview = <ThrowOnError extends boolean = false>(options: Options<ApiGetReviewReviewGetData, ThrowOnError>) => (options.client ?? client).get<ApiGetReviewReviewGetResponses, ApiGetReviewReviewGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/review',
    ...options
});

/**
 * Api Review
 *
 * Request a review, return review id
 */
export const apiRequestReview = <ThrowOnError extends boolean = false>(options: Options<ApiReviewReviewPostData, ThrowOnError>) => (options.client ?? client).post<ApiReviewReviewPostResponses, ApiReviewReviewPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/review',
    ...options
});

/**
 * Api Get Review Of Submission
 *
 * Get review of a Submission
 */
export const apiGetReviewOf = <ThrowOnError extends boolean = false>(options: Options<ApiGetReviewOfSubmissionReviewOfGetData, ThrowOnError>) => (options.client ?? client).get<ApiGetReviewOfSubmissionReviewOfGetResponses, ApiGetReviewOfSubmissionReviewOfGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/review/of',
    ...options
});

/**
 * Api Average Score
 */
export const apiGetStatistics = <ThrowOnError extends boolean = false>(options?: Options<ApiAverageScoreStatisticsGetData, ThrowOnError>) => (options?.client ?? client).get<ApiAverageScoreStatisticsGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/statistics/',
    ...options
});

/**
 * Api Get Submissions
 *
 * Get all submissions
 */
export const apiGetSubmissions = <ThrowOnError extends boolean = false>(options?: Options<ApiGetSubmissionsSubmissionsGetData, ThrowOnError>) => (options?.client ?? client).get<ApiGetSubmissionsSubmissionsGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/submissions',
    ...options
});

/**
 * Api Delete Submission
 *
 * Delete a submission
 */
export const apiDeleteSubmission = <ThrowOnError extends boolean = false>(options: Options<ApiDeleteSubmissionSubmissionDeleteData, ThrowOnError>) => (options.client ?? client).delete<ApiDeleteSubmissionSubmissionDeleteResponses, ApiDeleteSubmissionSubmissionDeleteErrors, ThrowOnError>({
    responseType: 'json',
    url: '/submission',
    ...options
});

/**
 * Api Get Submission
 *
 * Get a single submission
 */
export const apiGetSubmission = <ThrowOnError extends boolean = false>(options: Options<ApiGetSubmissionSubmissionGetData, ThrowOnError>) => (options.client ?? client).get<ApiGetSubmissionSubmissionGetResponses, ApiGetSubmissionSubmissionGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/submission',
    ...options
});

/**
 * Api Submit
 *
 * Submit a submission
 */
export const apiSubmitSubmission = <ThrowOnError extends boolean = false>(options: Options<ApiSubmitSubmissionPostData, ThrowOnError>) => (options.client ?? client).post<ApiSubmitSubmissionPostResponses, ApiSubmitSubmissionPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/submission',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Api Get Topics
 *
 * Get all topics
 */
export const apiGetTopics = <ThrowOnError extends boolean = false>(options?: Options<ApiGetTopicsTopicsGetData, ThrowOnError>) => (options?.client ?? client).get<ApiGetTopicsTopicsGetResponses, ApiGetTopicsTopicsGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/topics',
    ...options
});

/**
 * Api Delete Topic
 *
 * Delete a topic
 */
export const apiDeleteTopic = <ThrowOnError extends boolean = false>(options: Options<ApiDeleteTopicTopicDeleteData, ThrowOnError>) => (options.client ?? client).delete<ApiDeleteTopicTopicDeleteResponses, ApiDeleteTopicTopicDeleteErrors, ThrowOnError>({
    responseType: 'json',
    url: '/topic',
    ...options
});

/**
 * Api Get Topic
 *
 * Get a single topic
 */
export const apiGetTopic = <ThrowOnError extends boolean = false>(options: Options<ApiGetTopicTopicGetData, ThrowOnError>) => (options.client ?? client).get<ApiGetTopicTopicGetResponses, ApiGetTopicTopicGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/topic',
    ...options
});

/**
 * Api Create Topic
 *
 * Request a topic
 */
export const apiCreateTopic = <ThrowOnError extends boolean = false>(options: Options<ApiCreateTopicTopicPostData, ThrowOnError>) => (options.client ?? client).post<ApiCreateTopicTopicPostResponses, ApiCreateTopicTopicPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/topic',
    ...options
});
