// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};

/**
 * Annotation
 */
export type Annotation = {
    /**
     * Target Text
     */
    target_text: string;
    /**
     * Context Before
     */
    context_before: string;
    /**
     * Type
     */
    type: 'grammar' | 'vocabulary' | 'coherence' | 'mechanics';
    /**
     * Replacement
     */
    replacement: string | null;
    /**
     * Feedback
     */
    feedback: string;
};

/**
 * DetailScore
 */
export type DetailScore = {
    /**
     * Grammar
     */
    grammar: number;
    /**
     * Vocabulary
     */
    vocabulary: number;
    /**
     * Organization
     */
    organization: number;
    /**
     * Task Fulfillment
     */
    task_fulfillment: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * P1DetailScore
 */
export type P1DetailScore = {
    /**
     * Grammar
     */
    grammar: number;
    /**
     * Visual Relevance Score
     */
    visual_relevance: number;
};

/**
 * P1SubmitBody
 */
export type P1SubmitBody = {
    /**
     * File
     */
    file: string;
    /**
     * Submission
     */
    submission: string;
};

/**
 * SlicedAnswer
 */
export type SlicedAnswer = {
    /**
     * Id
     */
    id: string;
    /**
     * Question Id
     */
    question_id: string;
    /**
     * Submission Id
     */
    submission_id: string;
    /**
     * Content
     */
    content: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * SlicedAnswerReview
 */
export type SlicedAnswerReview = {
    /**
     * Id
     */
    id: string;
    /**
     * Review Id
     */
    review_id: string;
    /**
     * Answer Id
     */
    answer_id: string;
    /**
     * Overall Score
     */
    overall_score: number;
    /**
     * Feedback
     */
    feedback: string;
    details: P1DetailScore;
    /**
     * Annotations
     */
    annotations: Array<Annotation>;
};

/**
 * SlicedOverallReview
 */
export type SlicedOverallReview = {
    /**
     * Id
     */
    id: string;
    /**
     * Review Id
     */
    review_id: string;
    /**
     * Score Range
     */
    score_range?: [
        number,
        number
    ] | null;
    /**
     * Level Achieved
     */
    level_achieved?: number | null;
    /**
     * Overall Feedback
     */
    overall_feedback?: string | null;
    /**
     * Summary Feedback
     */
    summary_feedback?: string | null;
    detail_score?: DetailScore | null;
    /**
     * Annotations
     */
    annotations?: Array<Annotation> | null;
    /**
     * Improvement Suggestions
     */
    improvement_suggestions?: Array<string> | null;
};

/**
 * SlicedReview
 */
export type SlicedReview = {
    /**
     * Id
     */
    id: string;
    /**
     * Topic Id
     */
    topic_id: string;
    status: Status;
    overall?: SlicedOverallReview | null;
    /**
     * Answers
     */
    answers?: Array<SlicedAnswerReview>;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * SlicedSubmission
 */
export type SlicedSubmission = {
    /**
     * Id
     */
    id: string;
    /**
     * Topic Id
     */
    topic_id: string;
    /**
     * Answers
     */
    answers?: Array<SlicedAnswer>;
    review?: SlicedReview | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * SlicedTopic
 */
export type SlicedTopic = {
    /**
     * Id
     */
    id: string;
    /**
     * Color
     */
    color: string;
    status: Status;
    type: TopicType;
    part: TopicPart;
    /**
     * Questions
     */
    questions?: Array<SlicedTopicQuestion> | null;
    /**
     * Submissions
     */
    submissions?: Array<SlicedSubmission>;
    /**
     * Reviews
     */
    reviews?: Array<SlicedReview>;
    summary: Summary | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * SlicedTopicQuestion
 */
export type SlicedTopicQuestion = {
    /**
     * Id
     */
    id: string;
    /**
     * Topic Id
     */
    topic_id: string;
    /**
     * Question
     */
    question: string | null;
    /**
     * Artist Prompt
     */
    artist_prompt: string | null;
    /**
     * File
     */
    file: string | null;
    /**
     * Keywords
     */
    keywords: [
        string,
        string
    ] | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * Statistics
 */
export type Statistics = {
    /**
     * Total Submission
     */
    total_submission: number;
    /**
     * Average Score
     */
    average_score: number;
    /**
     * Improvement Rate
     */
    improvement_rate: number;
    /**
     * Total Time
     */
    total_time: number;
};

/**
 * Status
 */
export type Status = 'pending' | 'failed' | 'done';

/**
 * SubmitBody
 */
export type SubmitBody = {
    /**
     * Submission
     */
    submission: string;
};

/**
 * Summary
 */
export type Summary = {
    /**
     * Summary
     */
    summary: string;
    /**
     * Description
     */
    description: string;
};

/**
 * TopicPart
 */
export type TopicPart = '1' | '2' | '3';

/**
 * TopicType
 */
export type TopicType = 'writing';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ApiGetReviewsReviewsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/reviews';
};

export type ApiGetReviewsReviewsGetResponses = {
    /**
     * Response Api Get Reviews Reviews Get
     *
     * Successful Response
     */
    200: Array<SlicedReview>;
};

export type ApiGetReviewsReviewsGetResponse = ApiGetReviewsReviewsGetResponses[keyof ApiGetReviewsReviewsGetResponses];

export type ApiGetReviewReviewGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Id
         */
        id: string;
    };
    url: '/review';
};

export type ApiGetReviewReviewGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiGetReviewReviewGetError = ApiGetReviewReviewGetErrors[keyof ApiGetReviewReviewGetErrors];

export type ApiGetReviewReviewGetResponses = {
    /**
     * Successful Response
     */
    200: SlicedReview;
};

export type ApiGetReviewReviewGetResponse = ApiGetReviewReviewGetResponses[keyof ApiGetReviewReviewGetResponses];

export type ApiReviewReviewPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Submission Id
         */
        submission_id: string;
    };
    url: '/review';
};

export type ApiReviewReviewPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiReviewReviewPostError = ApiReviewReviewPostErrors[keyof ApiReviewReviewPostErrors];

export type ApiReviewReviewPostResponses = {
    /**
     * Response Api Review Review Post
     *
     * Successful Response
     */
    200: string;
};

export type ApiReviewReviewPostResponse = ApiReviewReviewPostResponses[keyof ApiReviewReviewPostResponses];

export type ApiGetReviewOfSubmissionReviewOfGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Submission Id
         */
        submission_id: string;
    };
    url: '/review/of';
};

export type ApiGetReviewOfSubmissionReviewOfGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiGetReviewOfSubmissionReviewOfGetError = ApiGetReviewOfSubmissionReviewOfGetErrors[keyof ApiGetReviewOfSubmissionReviewOfGetErrors];

export type ApiGetReviewOfSubmissionReviewOfGetResponses = {
    /**
     * Response Api Get Review Of Submission Review Of Get
     *
     * Successful Response
     */
    200: SlicedReview | null;
};

export type ApiGetReviewOfSubmissionReviewOfGetResponse = ApiGetReviewOfSubmissionReviewOfGetResponses[keyof ApiGetReviewOfSubmissionReviewOfGetResponses];

export type ApiAverageScoreStatisticsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/statistics/';
};

export type ApiAverageScoreStatisticsGetResponses = {
    /**
     * Successful Response
     */
    200: Statistics;
};

export type ApiAverageScoreStatisticsGetResponse = ApiAverageScoreStatisticsGetResponses[keyof ApiAverageScoreStatisticsGetResponses];

export type ApiGetSubmissionsSubmissionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/submissions';
};

export type ApiGetSubmissionsSubmissionsGetResponses = {
    /**
     * Response Api Get Submissions Submissions Get
     *
     * Successful Response
     */
    200: Array<SlicedSubmission>;
};

export type ApiGetSubmissionsSubmissionsGetResponse = ApiGetSubmissionsSubmissionsGetResponses[keyof ApiGetSubmissionsSubmissionsGetResponses];

export type ApiDeleteSubmissionSubmissionDeleteData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Id
         */
        id: string;
    };
    url: '/submission';
};

export type ApiDeleteSubmissionSubmissionDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiDeleteSubmissionSubmissionDeleteError = ApiDeleteSubmissionSubmissionDeleteErrors[keyof ApiDeleteSubmissionSubmissionDeleteErrors];

export type ApiDeleteSubmissionSubmissionDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiGetSubmissionSubmissionGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Id
         */
        id: string;
    };
    url: '/submission';
};

export type ApiGetSubmissionSubmissionGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiGetSubmissionSubmissionGetError = ApiGetSubmissionSubmissionGetErrors[keyof ApiGetSubmissionSubmissionGetErrors];

export type ApiGetSubmissionSubmissionGetResponses = {
    /**
     * Successful Response
     */
    200: SlicedSubmission;
};

export type ApiGetSubmissionSubmissionGetResponse = ApiGetSubmissionSubmissionGetResponses[keyof ApiGetSubmissionSubmissionGetResponses];

export type ApiSubmitSubmissionPostData = {
    /**
     * Body
     */
    body: SubmitBody | Array<P1SubmitBody>;
    path?: never;
    query: {
        /**
         * Part
         */
        part: string;
        /**
         * Topic Id
         */
        topic_id: string;
    };
    url: '/submission';
};

export type ApiSubmitSubmissionPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiSubmitSubmissionPostError = ApiSubmitSubmissionPostErrors[keyof ApiSubmitSubmissionPostErrors];

export type ApiSubmitSubmissionPostResponses = {
    /**
     * Successful Response
     */
    200: SlicedSubmission;
};

export type ApiSubmitSubmissionPostResponse = ApiSubmitSubmissionPostResponses[keyof ApiSubmitSubmissionPostResponses];

export type ApiGetTopicsTopicsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/topics';
};

export type ApiGetTopicsTopicsGetResponses = {
    /**
     * Response Api Get Topics Topics Get
     *
     * Successful Response
     */
    200: Array<SlicedTopic>;
};

export type ApiGetTopicsTopicsGetResponse = ApiGetTopicsTopicsGetResponses[keyof ApiGetTopicsTopicsGetResponses];

export type ApiDeleteTopicTopicDeleteData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Id
         */
        id: string;
    };
    url: '/topic';
};

export type ApiDeleteTopicTopicDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiDeleteTopicTopicDeleteError = ApiDeleteTopicTopicDeleteErrors[keyof ApiDeleteTopicTopicDeleteErrors];

export type ApiDeleteTopicTopicDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiGetTopicTopicGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Id
         */
        id: string;
    };
    url: '/topic';
};

export type ApiGetTopicTopicGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiGetTopicTopicGetError = ApiGetTopicTopicGetErrors[keyof ApiGetTopicTopicGetErrors];

export type ApiGetTopicTopicGetResponses = {
    /**
     * Successful Response
     */
    200: SlicedTopic;
};

export type ApiGetTopicTopicGetResponse = ApiGetTopicTopicGetResponses[keyof ApiGetTopicTopicGetResponses];

export type ApiCreateTopicTopicPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Part
         */
        part: '1' | '2' | '3';
        /**
         * P1 Count
         */
        p1_count?: number;
    };
    url: '/topic';
};

export type ApiCreateTopicTopicPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiCreateTopicTopicPostError = ApiCreateTopicTopicPostErrors[keyof ApiCreateTopicTopicPostErrors];

export type ApiCreateTopicTopicPostResponses = {
    /**
     * Successful Response
     */
    200: SlicedTopic;
};

export type ApiCreateTopicTopicPostResponse = ApiCreateTopicTopicPostResponses[keyof ApiCreateTopicTopicPostResponses];
